### ISSUE TITLE
typescript defs

### ISSUE THREAD

**Issue by unicomp21** [repalash/xatlas-three#2]
I'm trying to use xatlas w/ babylonjs and typescript, should I be using xatlas-three?  I cannot find typescript type defs in xatlasjs.

**Comment by repalash** [comment]
Hi, this repo xatlas-three is for using xatlas.js in three.js. Some changes might be required in the Unwrapper to use it in Babylon. 
xatlas.js doesn't have typescript definitions right now, but you can use it by @ts-ignore(similar to how it is used in this, see XAtlasJs.ts) or adding xatlasjs to your globals.d.ts
I can probably add ts definitions in some days to xatlasjs. Would you mind creating an issue there, I have enabled it now.
